/*
 * Arcade — the small shared layer every game in this folder sits on.
 *
 * No build step and no CDN: the only things it leans on live in games/vendor/,
 * so a game keeps working offline and on GitHub Pages alike.
 *
 * Arcade.Store   persistent high scores / settings (survives a blocked localStorage)
 * Arcade.Input   keyboard + touch + gamepad behind one set of actions
 * Arcade.Sfx     retro sound effects generated by jsfxr, no audio files
 * Arcade.Loop    fixed-timestep loop that pauses with the tab
 * Arcade.fit     letterboxed, pixel-crisp canvas scaling
 * Arcade.loadFont loads the bundled Press Start 2P face
 */
(function (global) {
  'use strict';

  var NS = 'arcade:';

  /* ---------------------------------------------------------------- store */

  var Store = {
    get: function (key, fallback) {
      try {
        var raw = localStorage.getItem(NS + key);
        return raw === null ? fallback : JSON.parse(raw);
      } catch (e) {
        return fallback;
      }
    },
    set: function (key, value) {
      try {
        localStorage.setItem(NS + key, JSON.stringify(value));
        return true;
      } catch (e) {
        return false;
      }
    },
    /** Record a score for a game and return the best one seen so far. */
    best: function (gameId, score) {
      var key = 'best:' + gameId;
      var best = Math.max(Number(Store.get(key, 0)) || 0, Number(score) || 0);
      Store.set(key, best);
      return best;
    }
  };

  /* ---------------------------------------------------------------- input */

  var KEY_MAP = {
    ArrowLeft: 'left', KeyA: 'left',
    ArrowRight: 'right', KeyD: 'right',
    ArrowUp: 'up', KeyW: 'up',
    ArrowDown: 'down', KeyS: 'down',
    Space: 'action', KeyZ: 'action', Enter: 'action',
    Escape: 'pause', KeyP: 'pause',
    KeyM: 'mute'
  };

  // Gamepad buttons that map onto the same actions (standard mapping).
  var PAD_MAP = { 0: 'action', 1: 'action', 9: 'pause', 12: 'up', 13: 'down', 14: 'left', 15: 'right' };

  function Input(opts) {
    opts = opts || {};
    this.surface = opts.surface || global.document.body;
    this.down = Object.create(null);   // action -> true while held
    this.hit = Object.create(null);    // action -> true until endFrame()
    this.pointer = { x: 0, y: 0, active: false };
    this._bind();
  }

  Input.prototype._press = function (action) {
    if (!action) return;
    if (!this.down[action]) this.hit[action] = true;
    this.down[action] = true;
  };

  Input.prototype._release = function (action) {
    if (action) this.down[action] = false;
  };

  Input.prototype._bind = function () {
    var self = this;

    global.addEventListener('keydown', function (e) {
      var action = KEY_MAP[e.code];
      if (!action) return;
      // Space and the arrows scroll the page otherwise, which ruins a game.
      e.preventDefault();
      if (!e.repeat) self._press(action);
    });

    global.addEventListener('keyup', function (e) {
      self._release(KEY_MAP[e.code]);
    });

    // Touch: left third steers left, right third steers right, the middle acts.
    function zoneOf(e) {
      var box = self.surface.getBoundingClientRect();
      var x = (e.clientX - box.left) / (box.width || 1);
      if (x < 0.33) return 'left';
      if (x > 0.67) return 'right';
      return 'action';
    }

    this.surface.addEventListener('pointerdown', function (e) {
      self.pointer.x = e.clientX;
      self.pointer.y = e.clientY;
      self.pointer.active = true;
      self._touchZone = zoneOf(e);
      self._press(self._touchZone);
      self._press('touch');
    });

    function endPointer() {
      self.pointer.active = false;
      self._release(self._touchZone);
      self._release('touch');
      self._touchZone = null;
    }

    global.addEventListener('pointerup', endPointer);
    global.addEventListener('pointercancel', endPointer);

    global.addEventListener('pointermove', function (e) {
      self.pointer.x = e.clientX;
      self.pointer.y = e.clientY;
    });

    // A key held when the tab loses focus would stay stuck down forever.
    global.addEventListener('blur', function () {
      self.down = Object.create(null);
    });
  };

  Input.prototype._pollPads = function () {
    if (!global.navigator || !global.navigator.getGamepads) return;
    var pads = global.navigator.getGamepads();
    for (var i = 0; i < pads.length; i++) {
      var pad = pads[i];
      if (!pad) continue;
      for (var b in PAD_MAP) {
        var button = pad.buttons[b];
        if (button && button.pressed) this._press(PAD_MAP[b]);
        else this._release(PAD_MAP[b]);
      }
      var ax = pad.axes[0] || 0;
      if (ax < -0.4) this._press('left'); else this._release('left');
      if (ax > 0.4) this._press('right'); else this._release('right');
    }
  };

  /** True while the action is held. */
  Input.prototype.held = function (action) {
    this._pollPads();
    return !!this.down[action];
  };

  /** True only on the frame the action started — cleared by endFrame(). */
  Input.prototype.pressed = function (action) {
    this._pollPads();
    return !!this.hit[action];
  };

  /** Horizontal / vertical intent as -1, 0 or 1. */
  Input.prototype.axis = function () {
    return {
      x: (this.held('right') ? 1 : 0) - (this.held('left') ? 1 : 0),
      y: (this.held('down') ? 1 : 0) - (this.held('up') ? 1 : 0)
    };
  };

  /** Call once per frame, after reading input. */
  Input.prototype.endFrame = function () {
    this.hit = Object.create(null);
  };

  /* ------------------------------------------------------------------ sfx */

  var Sfx = {
    enabled: Store.get('sfx', true),
    _cache: Object.create(null),

    /** Give a name its own sound; `preset` is a jsfxr generator name. */
    define: function (name, preset) {
      if (!global.jsfxr) return false;
      try {
        this._cache[name] = global.jsfxr.sfxr.generate(preset || 'blipSelect');
        return true;
      } catch (e) {
        return false;
      }
    },

    play: function (name, preset) {
      if (!this.enabled || !global.jsfxr) return;
      if (!this._cache[name] && !this.define(name, preset || name)) return;
      try {
        global.jsfxr.sfxr.play(this._cache[name]);
      } catch (e) {
        /* an autoplay block is not worth breaking the game over */
      }
    },

    toggle: function () {
      this.enabled = !this.enabled;
      Store.set('sfx', this.enabled);
      return this.enabled;
    }
  };

  /* ----------------------------------------------------------------- loop */

  function Loop(step, opts) {
    opts = opts || {};
    this.step = step;                        // step(dt) — dt is always fixed
    this.hz = opts.hz || 60;
    this.dt = 1 / this.hz;
    this.maxSteps = opts.maxSteps || 5;      // never spiral after a long stall
    this.running = false;
    this._acc = 0;
    this._last = 0;
    this._frame = this._frame.bind(this);

    var self = this;
    global.document.addEventListener('visibilitychange', function () {
      if (global.document.hidden) self.stop();
      else self.start();
    });
  }

  Loop.prototype._frame = function (now) {
    if (!this.running) return;
    var elapsed = Math.min((now - this._last) / 1000, 0.25);
    this._last = now;
    this._acc += elapsed;

    var steps = 0;
    while (this._acc >= this.dt && steps < this.maxSteps) {
      this.step(this.dt);
      this._acc -= this.dt;
      steps++;
    }
    if (steps === this.maxSteps) this._acc = 0;

    global.requestAnimationFrame(this._frame);
  };

  Loop.prototype.start = function () {
    if (this.running) return;
    this.running = true;
    this._last = global.performance.now();
    this._acc = 0;
    global.requestAnimationFrame(this._frame);
  };

  Loop.prototype.stop = function () {
    this.running = false;
  };

  /* ---------------------------------------------------------------- canvas */

  /**
   * Scale a canvas to the largest whole multiple of its base size that fits,
   * so pixel art stays sharp instead of blurring between texels.
   */
  function fit(canvas, baseWidth, baseHeight) {
    canvas.width = baseWidth;
    canvas.height = baseHeight;
    canvas.style.imageRendering = 'pixelated';

    function apply() {
      var box = canvas.parentElement || global.document.body;
      var available = box.getBoundingClientRect();
      var scale = Math.min(available.width / baseWidth, available.height / baseHeight);
      if (scale >= 1) scale = Math.floor(scale);
      if (scale <= 0) scale = Math.max(available.width / baseWidth, 0.1);
      canvas.style.width = Math.round(baseWidth * scale) + 'px';
      canvas.style.height = Math.round(baseHeight * scale) + 'px';
    }

    apply();
    global.addEventListener('resize', apply);
    global.addEventListener('orientationchange', apply);
    return apply;
  }

  /* ----------------------------------------------------------------- font */

  /** Load the bundled arcade face; resolves false rather than throwing. */
  function loadFont(url, family) {
    family = family || 'Press Start 2P';
    if (!global.FontFace || !global.document.fonts) return Promise.resolve(false);
    var face = new global.FontFace(family, 'url(' + url + ')');
    return face.load().then(function (loaded) {
      global.document.fonts.add(loaded);
      return true;
    }).catch(function () {
      return false;
    });
  }

  global.Arcade = {
    Store: Store,
    Input: Input,
    Sfx: Sfx,
    Loop: Loop,
    fit: fit,
    loadFont: loadFont,
    version: '1.0.0'
  };
}(window));
